### Getting all content
GET http://localhost:8080/api

### Getting one text
GET http://localhost:8080/api/1

### Trying to add new content
POST http://localhost:8080/api
Content-Type: application/json

{
  "title" : "First",
  "genre" : "YA",
  "wordCount" : "2000"
}

### Updating completeness (true)
PUT http://localhost:8080/api/0/complete

### Updating completeness (false)
PUT http://localhost:8080/api/0/incomplete

### Trying to start a timer

PUT http://localhost:8080/api/1/start

### Trying to end a timer

PUT http://localhost:8080/api/1/end


### Deleting a text
DELETE http://localhost:8080/api/1/delete

